spring.application.name=helpdesk-backend

spring.datasource.url=jdbc:postgresql://localhost:5433/helpdesk_db
spring.datasource.username=helpdesk_user
spring.datasource.password=helpdesk_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

helpdesk.jwt.secret=chave-secreta-portal-helpdesk-troque-em-producao-123456
helpdesk.jwt.expiracao-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs